---
- hosts: all
  gather_facts: yes
  tasks:
  - name: Distribution version
    when: ansible_os_family == 'Debian'
    debug: 
      msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }}.{{ ansible_distribution_minor_version }}"
  - name: Kernel version
    debug: 
      msg: "Kernel: {{ ansible_kernel }}"
  - name: Uptime
    shell: /usr/bin/uptime
    register: result
  - debug: msg="{{ result.stdout }}"
