---
- hosts: all

  tasks:
    - name: Update Repository Cache on Debian Servers
      when: ansible_os_family == 'Debian'
      apt:
        force_apt_get: yes
        update_cache: yes

    - name: Update Packages on Debian Servers
      when: ansible_os_family == 'Debian'
      apt:
        force_apt_get: yes
        upgrade: dist

    - name: Update Cleanup on Debian Servers
      when: ansible_os_family == 'Debian'
      apt:
        force_apt_get: yes
        autoremove: yes
        autoclean: yes
        clean: yes
